### ISSUE TITLE
"No module named decoratorOptions.ignore_functions"

### ISSUE THREAD

**Issue by Baralabite** [salesforce/decorator-operations#2]
Python Version 3.1.1

![image](https://user-images.githubusercontent.com/1272191/206636835-cf600dc5-ea4e-4694-9ce0-ceefd36c6f8e.png)

I tried to use the throttle decorator, but there was an import error that appeared to be internal to decoratorOperations. The library was installed by downloading a ZIP of the code repo, and then installing using `pip install .`

![image](https://user-images.githubusercontent.com/1272191/206637596-b80866f6-2cdb-4aec-ad05-6fc291746116.png)

**Comment by KarlPatach** [comment]
You're completely right, thanks @Baralabite !

**Comment by KarlPatach** [comment]
You're completely right, thanks @Baralabite ! I've just reopened the issue to make sure this actually fixed your problem.

In addition to this, if you start using this project, would you be interested in having it being available through PyPI directly ? This was not in my immediate priorities but could be done

**Comment by KarlPatach** [comment]
Closing the issue since no more answer from requester, still open for discussions if needed
